### ISSUE TITLE
createCard method?

### ISSUE THREAD

**Issue by adixon** [zburke/omnipay-bluepay#1]
Any thoughts about implementing token billing (http://omnipay.thephpleague.com/api/token-billing/) for BluePay? Have you looked into whether their api supports it?

**Comment by zburke** [comment]
Based on https://www.bluepay.com/payment-processing/pci-compliance/tokenization/ I'm pretty sure the API supports token-based payments. I don't have the time to work on this currently but would be happy to merge a PR.

**Comment by adixon** [comment]
Great, thanks for the link. This looks like where I should be going with this:
https://github.com/jslingerland/BluePay-Sample-Code/blob/master/PHP/Transactions/Store_Payment_Information.php
PR upcoming.

**Comment by zburke** [comment]
Fixed in #2
